# Generated by Django 4.1.3 on 2022-11-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curator',
            options={'verbose_name': 'Куратор', 'verbose_name_plural': 'Кураторы'},
        ),
        migrations.AlterModelOptions(
            name='direction_of_studying',
            options={'verbose_name': 'Направление подготовки', 'verbose_name_plural': 'Направления подготовки'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='curator',
            name='direction_of_studying',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='university.direction_of_studying', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='curator',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='curator',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='curator',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='direction_of_studying',
            name='direction_of_studying',
            field=models.CharField(max_length=255, unique=True, verbose_name='Направление подготовки'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.direction_of_studying', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Предмет'),
        ),
    ]
