# Generated by Django 4.1.3 on 2022-11-07 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_curator_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curator',
            name='direction_of_studying',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.direction_of_studying', verbose_name='Направление'),
        ),
    ]
