# Generated by Django 4.1.3 on 2022-11-07 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_curator_direction_of_studying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curator',
            name='direction_of_studying',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.direction_of_studying', verbose_name='Направление'),
        ),
    ]
