# Generated by Django 4.1.3 on 2022-11-07 19:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_curator_direction_of_studying'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=500)])),
                ('direction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.direction_of_studying')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('studying_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.education_group', verbose_name='Учебная группа')),
            ],
        ),
    ]
