# Generated by Django 4.1.3 on 2022-11-07 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_education_group_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education_group',
            options={'verbose_name': 'Учебная группа', 'verbose_name_plural': 'Учебные группы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterField(
            model_name='education_group',
            name='group_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=500)]),
        ),
    ]
