# Generated by Django 4.1.3 on 2022-11-07 19:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_alter_education_group_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_group',
            name='group_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=500)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='studying_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.education_group', verbose_name='Учебная группа'),
        ),
    ]
