# Generated by Django 4.1.3 on 2022-11-07 20:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_alter_education_group_group_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_group',
            name='direction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.direction_of_studying', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='education_group',
            name='group_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=500)], verbose_name='Номер группы'),
        ),
    ]
