# Generated by Django 4.1.3 on 2022-11-07 20:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_alter_education_group_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studying_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.education_group', validators=[django.core.validators.MaxValueValidator(limit_value=3)], verbose_name='Учебная группа'),
        ),
    ]
