# Generated by Django 4.1.3 on 2022-11-07 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_alter_student_studying_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studying_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.education_group', verbose_name='Учебная группа'),
        ),
    ]
