# Generated by Django 4.1.3 on 2022-11-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_alter_education_group_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direction_of_studying',
            old_name='direction_of_studying',
            new_name='direction',
        ),
    ]
