# Generated by Django 4.1.3 on 2022-11-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_rename_direction_of_studying_direction_of_studying_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='direction',
            new_name='direction_name',
        ),
    ]
