# Generated by Django 4.1.3 on 2022-11-08 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0013_rename_direction_subject_direction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='curator',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
            preserve_default=False,
        ),
    ]
