# Generated by Django 4.1.3 on 2022-11-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_alter_curator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curator',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='curator',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='curator',
            name='patronymic',
        ),
    ]
