# Generated by Django 4.1.3 on 2022-11-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0017_remove_curator_first_name_remove_curator_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curator',
            name='first_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curator',
            name='last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curator',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='curator',
            name='direction_of_studying',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_curator', to='university.direction_of_studying', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='direction_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_dir', to='university.direction_of_studying', verbose_name='Направление'),
        ),
    ]
