# Generated by Django 4.1.3 on 2022-11-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_curator_first_name_curator_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curator',
            name='direction_of_studying',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_curator', to='university.direction_of_studying', verbose_name='Направление'),
        ),
    ]
